name: Port Message Sender
description: Send Reminders and Reports from Port to Slack
author: port-labs
branding:
  icon: alert-circle
inputs:
  port_client_id:
    description: 'The Port Client ID to use to authenticate with the API'
    required: true
  port_client_secret:
    description: 'The Port Client Secret to use to authenticate with the API'
    required: true
  slack_webhook_url:
    description: 'The URL of the Slack channel webhook to use to send messages'
    required: true
  message_kind:
    description: 'The kind of message to send, either "scorecard_reminder" or "scorecard_report"'
    required: true
  blueprint:
    description: 'The identifier of the blueprint in Port which you want to send reminders and reports about'
    required: true
  scorecard:
    description: 'The scorecard to use to send reminders and reports about'
    required: true
  filter_rule:
    description: 'filter to use to filter the response, for example: {"property": "$team","operator": "containsAny","value": ["Backend"]}'
    required: false
runs:
  using: docker
  image: Dockerfile
